dist: trusty

language: node_js

node_js:
  - lts/*

before_script:
  - rm -rf docs/.vuepress/dist || exit 0

install:
  - yarn

script:
  - yarn docs:build
  - echo 'flutterworld.site' > docs/.vuepress/dist/CNAME

cache: yarn

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
